name: Figure out the best label

on:
  workflow_dispatch:
    inputs:
      pr_name:
        description: |
          PR number for core, or "repo/PR#" if you need staging app
          for another project (will notify in the "repo")
        required: true
        type: string
        hint: "Hey, I'm a hint!"
        placeholder: "placeholder here"

jobs:
  dummy:
    steps:
      - run: echo "Hello, world"
        shell: bash
