name: "Evaluate PR lifecycle"
on:
  pull_request:
    types: [opened, synchronize, closed, reopened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "What happened: ${{ github.event.action }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
