name: "Evaluate PR lifecycle"
on:
  pull_request:
    types: [opened, synchronize, closed, reopened]
  pull_request_target:
    types: [closed]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh pr comment ${{ github.event.pull_request.number }} \
            -R "${{ github.repository }}" \
            -b "What happened: ${{ github.event_name }} ${{ github.event.action }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
