name: Dummy release
on:
  workflow_dispatch: {}

jobs:
  release:
    name: "Simulate a release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure git commiter info
        run: |
          invoker="${{ github.event.sender.login }}"
          if [ "${invoker}" ]
          then
            invoker_name="$(gh api users/${invoker} --template '{{ .name }}')"
          fi
          [ "$invoker_name" ] || invoker_name='Github Bot'
          encoded_token=$(echo -n "${GH_TOKEN}" | base64)
          git config user.name "${invoker_name}"
          git config user.email '27407+timon@users.noreply.github.com'
          git config http.https://github.com/.extraheader "AUTHORIZATION: Basic ${encoded_token}"
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Dump various info
        run: |
          git config -l
          echo ""
          echo "Github context"
          echo '${{ toJSON(github) }}' | jq .
      - name: Perform a release
        run: |
          echo "Release: $(date +'%F %T %Z')" >> releases
          release_tag=v$(date +%F.%H%M)
          git add releases && git commit -m "Release ${release_tag}"
          git tag "${release_tag}"
          git push --tags origin master

